name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: brew install nasm i686-elf-gcc

    - name: build
      run: make all

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: sudo apt install nasm

    - name: build
      run: make all

    - uses: actions/upload-artifact@v4
      with:
        name: kernel/bin/kernel.elf
        path: kernel.elf

    - uses: actions/upload-artifact@v4
      with:
        name: kernel/bin/kernel.elf.dump
        path: kernel.elf.dump

    - uses: actions/upload-artifact@v4
      with:
        name: initrd.img
        path: initrd.img

